FantasticFiesta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include

from dashboard.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    url(r'^$', DashboardView.as_view(), name="dashboard"),
    path('account/', include(('login.urls', 'login'), namespace='login')),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.conf.urls import url
from event.views import CreateEvent, UpdateEvent, DeleteEvent

urlpatterns = [
    url(r'^new', CreateEvent.as_view(), name='create_event'),
    url(r'^update/(?P<pk>\d+)', UpdateEvent.as_view(), name='update_event'),
    url(r'^delete/(?P<pk>\d+)', DeleteEvent.as_view(), name='delete_event')
]

event/models.py
from django.contrib.auth.models import User
from django.db import models

from contact.models import Contact


class Event(models.Model):

    STATUS_CHOICE = (
        ('P', 'Planned'),
        ('O', 'Ongoing'),
        ('C', 'Completed')
    )

    class Meta:
        verbose_name_plural = "Events"

    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=STATUS_CHOICE)
    note = models.TextField()
    date = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

event/forms.py
from django.forms.models import ModelForm
from event.models import Event


class CreateEventForm(ModelForm):

    class Meta:
        fields = ['contact', 'status', 'note', 'date']
        model = Event
        labels = {
            'date': 'Date and Time'
        }
        help_texts = {
            'date': 'Date and Time in format DD/MM/YYYY hh:mm',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['contact'].queryset = self.fields['contact'].queryset.filter(
            added_by=user)

event/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from event.forms import CreateEventForm
from event.models import Event


class CreateEvent(CreateView, LoginRequiredMixin):
    model = Event
    template_name = 'event/create_event.html'
    form_class = CreateEventForm

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        event = Event()
        if form.is_valid():
            event.contact = form.cleaned_data['contact']
            event.date = form.cleaned_data['date']
            event.note = form.cleaned_data['note']
            event.status = form.cleaned_data['status']
            event.user = self.request.user
            event.save()
            return HttpResponseRedirect('/')
        else:
            return render(request, self.template_name, {'form': form})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class UpdateEvent(UpdateView, LoginRequiredMixin):
    model = Event
    template_name = 'event/update_event.html'
    form_class = CreateEventForm
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class DeleteEvent(DeleteView, LoginRequiredMixin):
    model = Event
    template_name = 'event/delete_event.html'
    success_url = '/'

event/templates/event/create_event.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Event</h3>
                </div>
                <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' with form=form %}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

event/templates/event/delete_event.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Delete Event</h3>
                </div>
                <div class="panel-body">
                    <p>Are you sure you want to delete this event?</p>
                <form method="post" novalidate>
                    {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

event/templates/event/event_list.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
 <div class="container">
    <br>
        <div class="row">
            <div class="col">
                <h3>Event</h3>
            </div>
            <div class="col text-right">
                 <a class="btn btn-success" href="{% url "event:create_event" %}">Add Event</a>
            </div>


            <table class="table">
                <thead>
                    <tr>
                        <th>Contact</th>
                        <th>Date</th>
                        <th>Note</th>
                        <th>Status</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                {% for event in events %}
                    <tr>
                        <td>{{event.contact.last_name}}, {{event.contact.first_name}}</td>
                        <td>{{event.date}}</td>
                        <td>{{event.note}}</td>
                        <td>{{event.get_status_display}}</td>
                        <td><a class="btn btn-success" href="{% url "event:update_event" pk=event.id%}">Edit Event</a></td>
                        <td><a class="btn btn-success" href="{% url "event:delete_event" pk=event.id%}">Delete Event</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
{% endblock %}

event/templates/event/update_event.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Update Event</h3>
                </div>
                <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' with form=form %}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}