FantasticFiesta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include

from dashboard.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    url(r'^$', DashboardView.as_view(), name="dashboard"),
    path('account/', include(('login.urls', 'login'), namespace='login')),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.conf.urls import url
from event.views import CreateEvent, UpdateEvent, DeleteEvent

urlpatterns = [
    url(r'^new', CreateEvent.as_view(), name='create_event'),
    url(r'^update/(?P<pk>\d+)', UpdateEvent.as_view(), name='update_event'),
    url(r'^delete/(?P<pk>\d+)', DeleteEvent.as_view(), name='delete_event')
]

login/urls.py
from django.conf.urls import url
from login.forms import LoginForm
from django.contrib.auth import views as auth_views
from login.views import UserCreateView

app_name = "authentication"

urlpatterns =[
    url(r'^$', auth_views.LoginView.as_view(template_name="system/login.html", authentication_form=LoginForm), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'^register/$', UserCreateView.as_view(), name="register"),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Username", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'})
    )

    password = forms.CharField(
        label="Password", max_length=30, widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'})
    )

login/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateView(CreateView):
    model = User

    template_name = 'login/create_user.html'
    form_class = UserCreationForm

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        user = User()
        if form.is_valid():

            user.username = form.cleaned_data['username']
            user.password = form.cleaned_data['password2']
            user.set_password(user.password)
            user.save()

            return HttpResponseRedirect(reverse("authentication:login"))

        else:
            return render(request, self.template_name, {'form': form})

templates/system/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' with form=form %}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                    <a class="btn btn-success" href="{% url "authentication:register" %}" role="button">Register</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}