FantasticFiesta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include

from dashboard.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    url(r'^$', DashboardView.as_view(), name="dashboard"),
    path('account/', include(('login.urls', 'login'), namespace='login')),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf.urls import url
from contact.views import CreateContact, ListContact, DetailContact, DeleteContact, UpdateContact

urlpatterns = [
    url(r'^new', CreateContact.as_view(), name='create_contact'),
    url(r'^$', ListContact.as_view(), name='list_contact'),
    url(r'^detail/(?P<pk>\d+)', DetailContact.as_view(), name='detail_contact'),
    url(r'^delete/(?P<pk>\d+)', DeleteContact.as_view(), name='delete_contact'),
    url(r'^update/(?P<pk>\d+)', UpdateContact.as_view(), name='update_contact'),
]

event/urls.py
from django.conf.urls import url
from event.views import CreateEvent, UpdateEvent, DeleteEvent

urlpatterns = [
    url(r'^new', CreateEvent.as_view(), name='create_event'),
    url(r'^update/(?P<pk>\d+)', UpdateEvent.as_view(), name='update_event'),
    url(r'^delete/(?P<pk>\d+)', DeleteEvent.as_view(), name='delete_event')
]

login/urls.py
from django.conf.urls import url
from login.forms import LoginForm
from django.contrib.auth import views as auth_views
from login.views import UserCreateView

app_name = "authentication"

urlpatterns =[
    url(r'^$', auth_views.LoginView.as_view(template_name="system/login.html", authentication_form=LoginForm), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'^register/$', UserCreateView.as_view(), name="register"),
]

templates/base.html
{%  load staticfiles %}

<link rel="stylesheet" href="{% static "app.css" %}"/>

<!Doctype html>
<html>
    <head>
        <title>Fantastic Fiesta</title>
    </head>

    <body>
   <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <a class="navbar-brand" href="/">Fantastic Fiesta</a>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "contact:list_contact" %}">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">Event</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
            </li>
             {% endif %}
        </ul>
    </nav>
    <div id="content">
            {% block content %} {% endblock %}
        </div>
    <script type="application/javascript" src="{% static "app.js" %}">
    </body>
</html>