FantasticFiesta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include

from dashboard.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    url(r'^$', DashboardView.as_view(), name="dashboard"),
    path('account/', include(('login.urls', 'login'), namespace='login')),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf.urls import url
from contact.views import CreateContact, ListContact, DetailContact, DeleteContact, UpdateContact

urlpatterns = [
    url(r'^new', CreateContact.as_view(), name='create_contact'),
    url(r'^$', ListContact.as_view(), name='list_contact'),
    url(r'^detail/(?P<pk>\d+)', DetailContact.as_view(), name='detail_contact'),
    url(r'^delete/(?P<pk>\d+)', DeleteContact.as_view(), name='delete_contact'),
    url(r'^update/(?P<pk>\d+)', UpdateContact.as_view(), name='update_contact'),
]

event/urls.py
from django.conf.urls import url
from event.views import CreateEvent, UpdateEvent, DeleteEvent

urlpatterns = [
    url(r'^new', CreateEvent.as_view(), name='create_event'),
    url(r'^update/(?P<pk>\d+)', UpdateEvent.as_view(), name='update_event'),
    url(r'^delete/(?P<pk>\d+)', DeleteEvent.as_view(), name='delete_event')
]

contact/models.py
import random

from django.db import models
from django.contrib.auth.models import User
# Create your models here.


def content_file_name(instance, filename):
    return '/'.join(['content', str(random.getrandbits(128))])


class Contact(models.Model):

    class Meta:
        verbose_name_plural = "Contacts"

    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    profil_picture = models.ImageField(upload_to=content_file_name)

    added_by = models.ForeignKey(
        User, on_delete=models.CASCADE
    )

    def __str__(self):
        return "%s, %s" % (
            self.last_name, self.first_name
        )

contact/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from contact.models import Contact


class ListContact(ListView, LoginRequiredMixin):
    model = Contact

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['contacts'] = Contact.objects.filter(added_by=self.request.user)

        return context


class CreateContact(CreateView, LoginRequiredMixin):
    model = Contact
    template_name = 'contact/create_contact.html'

    fields = ['first_name', 'last_name', 'email', 'profil_picture']

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        contact = Contact()
        if form.is_valid():
            contact.email = form.cleaned_data['email']
            contact.first_name = form.cleaned_data['first_name']
            contact.last_name = form.cleaned_data['last_name']
            contact.profil_picture = form.cleaned_data['profil_picture']
            contact.added_by = self.request.user
            contact.save()
            return HttpResponseRedirect('/contact/')
        else:
            return render(request, self.template_name, {'form': form})


class DetailContact(DetailView, LoginRequiredMixin):
    model = Contact
    template_name = 'contact/detail_contact.html'


class UpdateContact(UpdateView, LoginRequiredMixin):
    model = Contact
    template_name = 'contact/create_contact.html'

    fields = ['first_name', 'last_name', 'email', 'profil_picture']
    success_url = '/contact/'


class DeleteContact(DeleteView, LoginRequiredMixin):
    model = Contact
    template_name = 'contact/delete_contact.html'
    success_url = '/contact/'

contact/templates/contact/contact_list.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
 <div class="container">
    <br>
        <div class="row">
            <div class="col">
                <h3>Contact</h3>
            </div>
            <div class="col text-right">
                 <a class="btn btn-success" href="{% url "contact:create_contact" %}">Add Contact</a>
            </div>


            <table class="table">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Detail</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                 {% for contact in contacts %}
                    <tr>
                        <td>{{contact.first_name}}</td>
                        <td>{{contact.last_name}}</td>
                        <td>{{contact.email}}</td>
                        <td><a class="btn btn-success" href="{% url "contact:detail_contact" pk=contact.id %}">Detail</a></td>
                        <td><a class="btn btn-success" href="{% url "contact:update_contact" pk=contact.id %}">Edit Contact</a></td>
                        <td><a class="btn btn-success" href="{% url "contact:delete_contact" pk=contact.id %}">Delete Contact</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
{% endblock %}

contact/templates/contact/create_contact.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Contact</h3>
                </div>
                <div class="panel-body">
                <form enctype="multipart/form-data" method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' with form=form %}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact/delete_contact.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Delete Contact</h3>
                </div>
                <div class="panel-body">
                    <p>Are you sure you want to delete this contact?</p>
                <form method="post" novalidate>
                    {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact/detail_contact.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block content %}
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="/media/{{object.profil_picture}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{object.last_name}}, {{object.first_name}}</h5>
    <p class="card-text">{{object.email}}</p>
    <a href="{% url "contact:list_contact" %}" class="btn btn-primary">Go Back</a>
  </div>
</div>
{% endblock %}